variables:
  PROJECT_NAME: watchers
  ROOTPATH: /go/src/git.posc.in/cw
  GO_IMAGE: registry.posc.in/cw/infra/go
  DATADIR: /data/btc-data

stages:
  - test

image: $GO_IMAGE

before_script:
  - make dep

# Run local tests
local:
  stage: test
  script:
    - make lint
    - make test
    - make coverage
